name: command

on:
  workflow_dispatch:
  # pull_request:
  #   types: [opened, synchronize]
  #   paths:
  #     - .github/workflows/command.yml
  #     - docs/**
  #     - tests/**
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - .github/workflows/command.yml
  #     - docs/**
  #     - tests/**

permissions: read-all

jobs:
  command-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install requirements
        run: sudo apt install -y pv

      - name: Apostrophe code check
        env:
          TERM: xterm
          CLUSTER_NAME: kube1-test
        run: |
          ./run-k8s-eks-bottlerocket-fargate.sh readme_output_only > /dev/null
          if [[ $(grep \' "/tmp/README-${CLUSTER_NAME}.sh" | sort | uniq | wc -l) != "2" ]]; then
            echo "*** Additional apostrophe found. Please check the source code and remove them..."
            grep \' "/tmp/README-${CLUSTER_NAME}.sh" | sort | uniq
            exit 1
          fi

      - name: Clean disk space
        run: |
          df -h /
          rm -rf /usr/share/dotnet/
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h /

      - name: Run tests/tests.sh
        run: |
          sudo rm /usr/local/bin/helm
          script -e -c tests/tests.sh

      - name: Run tests/update_helmcharts.sh
        run: |
          tests/update_helmcharts.sh
